#!/bin/bash


RAW_GITHUB_URL=https://raw.githubusercontent.com/shan-shaji/setup-flutter/main

source "$RAW_GITHUB_URL/install_homebrew"
source "$RAW_GITHUB_URL/helpers/shell_helper"
source "$RAW_GITHUB_URL/install_java"
source "$RAW_GITHUB_URL/install_android_studio"
source "$RAW_GITHUB_URL/install_fvm"
source "$RAW_GITHUB_URL/install_vs_code"



# Install Homebrew
check_install_homebrew

# Reload shell configuration to apply PATH changes
reload_shell

# Install Android studio if not already installed
install_android_studio

# Install Visual Studio Code
install_vs_code

# Install FVM
install_fvm
