#!/bin/bash

# Install Homebrew if it's not already installed
which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Add Homebrew to the PATH if it's not already there
if [ "$(uname)" == "Darwin" ]; then
    # macOS
    if [ ! -f ~/.zshrc ]; then
        touch ~/.zshrc
    fi
    if ! grep -q 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zshrc; then
        (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zshrc
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Linux
    if ! grep -q 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' ~/.bashrc && ! grep -q 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' ~/.zshrc; then
        if [ -n "$ZSH_VERSION" ]; then
            echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.zshrc
        elif [ -n "$BASH_VERSION" ]; then
            echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.bashrc
        fi
    fi
fi

# Reload shell configuration to apply Homebrew PATH changes
if [ -n "$ZSH_VERSION" ]; then
    source ~/.zshrc
elif [ -n "$BASH_VERSION" ]; then
    source ~/.bashrc
fi

# Check if brew command is available
if ! command brew -v &> /dev/null; then
    echo "Homebrew not found. Please check the Homebrew installation and PATH setup."
    exit 1
fi

# Install Java if it's not already installed
brew list --cask adoptopenjdk/openjdk/adoptopenjdk8 || brew install --cask adoptopenjdk/openjdk/adoptopenjdk8

# Install Android Studio if it's not already installed
if [ "$(uname)" == "Darwin" ]; then
    if [ ! -d "/Applications/Android Studio.app" ]; then
        brew list --cask android-studio || brew install --cask android-studio
    fi
else
    brew list --cask android-studio || brew install --cask android-studio
fi

# Install Visual Studio Code if it's not already installed
if [ "$(uname)" == "Darwin" ]; then
    if [ ! -d "/Applications/Visual Studio Code.app" ]; then
        brew list --cask visual-studio-code || brew install --cask visual-studio-code
    fi
else
    brew list --cask visual-studio-code || brew install --cask visual-studio-code
fi

# Install FVM if it's not already installed
if ! brew list fvm &> /dev/null; then
    brew tap leoafarias/fvm
    brew install fvm
fi

# Set up the shell configuration file
if [ "$(uname)" == "Darwin" ]; then
    SHELL_CONFIG=~/.zshrc
else
    SHELL_CONFIG=~/.bashrc
fi

# Add FVM executable to the PATH in the shell configuration file
if ! grep -q 'export PATH="$HOME/fvm/default/bin"' $SHELL_CONFIG; then
     sed -i '' '1i\
        export PATH="$HOME/fvm/default/bin:$PATH"' $SHELL_CONFIG
fi

# Activate changes to shell configuration file
source $SHELL_CONFIG

# Install Flutter stable if it's not already installed
fvm list | grep 'stable' || fvm install stable

# Set Flutter global version to stable
fvm global stable

# Update PATH environment variable to point to the FVM-managed Flutter SDK
export PATH="$HOME/fvm/default/bin:$PATH"

# Run flutter doctor
flutter doctor

